version: "3.7"
services:
  frontend:
    image: programboard/frontend
    build:
      context: ./front
    ports:
      - 3000:3000
  backend:
    image: programboard/backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/programboard
    build:
      context: ./back
    ports:
      - 8080:8080
    depends_on:
      - db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: programboard
    ports:
      - "3306:3306"
    volumes:
      - ./init:/db/init.d
