version: "3.7"
services:
  frontend: 
    image: programboard/frontend
    container_name: "frontend"
    build: 
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules